### PR TITLE
Basic query-string based routing

### PR DESCRIPTION
**Pull request by ticky**
This adds some really simple query-string based routing to the application. Basically it means if you need to refresh your schema, you can mash ⌘R and it works just fine. As an extra liberty, it adds a "Logout" button to the toolbar so you can change authorisation in-app.

### CODE REVIEW

**Comment by keithpitt** [comment]
I love this idea, refreshing the GraphQL explorer is the worst thing ever especially in development...however there's a few security issues that we'll need to figure out before we can merge party this in :(

Currently our API Access Tokens for GraphQL can access all the things (no scoping to permissions or organisations) which means that from a security perspective, they're essentially the same as a password. This is just during the GraphQL Beta and we make that clear when you create a GraphQL API token (it's not ideal, but when we make it 1.0 we'll fix it).

If we put the API Access Token in the URL that means you can go to the explorer, leave it, and your API Access Token will be stored in plain text in your browser history, which smells a bit poo poo. Another idea is to store it in localStorage, but that has the same issue (storing it in plain text where a bad person could come along and steal it). You could argue that your Buildkite cookie is of the same security level, but at least we can expire that, where as an API token doesnt' have the same semantics. Cookies change all the time, but API Tokens are forever (sounds like a catchy marketing slogan)...

I wish I had an idea on how to fix it, but I'm afraid I don't :( The only way I can think to make the explore secure™ is to make the explorer a server side application (not just frontend js) where when you put your token in, it's stored in the session encrypted with a cookie, and logging out kills the session, like a proper website. That'd take a ton of effort and time, so the cost/benefit there is something to consider. 

Another idea is to use desktop GraphQL IDE in the short term that has all that stuff already built into it! There are a few of them on GitHub now that you can try!

**Comment by ticky** [comment]
I imagined that might be the case 😜 we could cookie it client-side, which would at least obfuscate it, but, I figure, if someone has physical access to someone’s computer, and wants their credentials, they can and will get them.

**Comment by toolmantim** [comment]
This would be great, if we just excluded the token from the URL but kept the rest as-is

**Comment by ticky** [comment]
> if we just excluded the token from the URL but kept the rest as-is

Where would the token go, then? `localStorage`?

**Comment by toolmantim** [comment]
Just a const?

**Comment by ticky** [comment]
> Just a const?

I mean, it’s user-supplied, so it couldn’t be :P

**Comment by toolmantim** [comment]
Sorry, I meant just a variable :)

**Comment by toolmantim** [comment]
Oh, I thought this PR added the GraphQL query to the URL string, so you could refresh/copy+paste — and that's why I was suggesting keeping the token as a variable. But this was all about the token gear. I see now.

**Pull request closed without merging**
